// Code generated by hero.
// source: /Users/codehex/Desktop/go/src/github.com/Code-Hex/vegeta/template/admin.html
// DO NOT EDIT!
package vegeta

import (
	"io"

	"github.com/shiyanhui/hero"
)

func AdminHTML(users []*User, args Args, w io.Writer) {
	_buffer := hero.GetBuffer()
	defer hero.PutBuffer(_buffer)
	_buffer.WriteString(`<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="IoTを用いた栽培中の植物のデータを管理するプロジェクトです。">
  <link href="/assets/css/main.css" rel="stylesheet">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  <title>`)
	_buffer.WriteString(`admin`)

	_buffer.WriteString(`</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light static-top v-navbar">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="/">Vegeta</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <i class="fa fa-bars"></i>
        </button>
      </div>
      <div id="navbarResponsive" class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item"><a class="nav-link" href="/contact">問い合わせ</a></li>
        </ul>
        <ul class="navbar-nav">
          `)
	if args.IsAuthed() {
		_buffer.WriteString(`
            <li class="nav-item dropdown show">
              <a class="nav-link dropdown-toggle dropdown-toggle-split" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user" aria-hidden="true"></i> ユーザー</a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="/mypage"><i class="fa fa-pagelines" aria-hidden="true"></i> 観察</a>
                <div class="dropdown-divider"></div>
                `)
		if args.IsAdmin() {
			_buffer.WriteString(`
                  <a class="dropdown-item" href="/mypage/admin"><i class="fa fa-lock" aria-hidden="true"></i> ユーザー管理パネル</a>
                `)
		} else {
			_buffer.WriteString(`
                  <a class="dropdown-item" href="/mypage/settings"><i class="fa fa-cog" aria-hidden="true"></i> 設定</a>
                `)
		}
		_buffer.WriteString(`
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/mypage/logout"><i class="fa fa-sign-out" aria-hidden="true"></i> ログアウト</a>
            </li>
          `)
	} else {
		_buffer.WriteString(`
            <li class="nav-item">
              <a class="nav-link" href="/login"><i class="fa fa-sign-in" aria-hidden="true"></i> ログイン</a>
            </li>
          `)
	}
	_buffer.WriteString(`
        </ul>
      </div>
    </div>
  </nav>
  `)
	_buffer.WriteString(`
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <div class="panel panel-default panel-table">
        <div class="panel-heading">
          <div class="row">
            <div class="col col-xs-6">
              <h3 class="panel-title">ユーザーリスト</h3>
            </div>
            <div class="col col-xs-6 text-right">
              <button type="button" class="btn btn-sm btn-primary btn-create">Create New</button>
            </div>
          </div>
        </div>
        <div class="panel-body">
          <table class="table table-striped table-bordered table-list">
            <thead>
              <tr>
                <th>
                  <em class="fa fa-cog"></em>
                </th>
                <th class="hidden-xs">ID</th>
                <th>Name</th>
                <th>Admin</th>
              </tr>
            </thead>
            <tbody>
              `)
	for _, user := range users {
		_buffer.WriteString(`
              <tr>
                <td align="center">
                  <a class="btn btn-default">
                    <em class="fa fa-pencil"></em>
                  </a>
                  <a class="btn btn-danger">
                    <em class="fa fa-trash"></em>
                  </a>
                </td>
                <td class="hidden-xs">`)
		hero.FormatUint(uint64(user.ID), _buffer)
		_buffer.WriteString(`</td>
                <td>`)
		hero.EscapeHTML(user.Name, _buffer)
		_buffer.WriteString(`</td>
                <td>`)
		hero.FormatBool(user.Admin, _buffer)
		_buffer.WriteString(`</td>
              </tr>
              `)
	}
	_buffer.WriteString(`
            </tbody>
          </table>
        </div>
        <div class="panel-footer">
          <div class="row">
            <div class="col col-xs-4">Page 1 of 5 </div>
            <div class="col col-xs-8">
              <ul class="pagination hidden-xs pull-right">
                <li>
                  <a href="#">1</a>
                </li>
                <li>
                  <a href="#">2</a>
                </li>
                <li>
                  <a href="#">3</a>
                </li>
                <li>
                  <a href="#">4</a>
                </li>
                <li>
                  <a href="#">5</a>
                </li>
              </ul>
              <ul class="pagination visible-xs pull-right">
                <li>
                  <a href="#">&#171;</a>
                </li>
                <li>
                  <a href="#">&#187;</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
`)

	_buffer.WriteString(`
  <footer class="footer" role="contentinfo">
    <p>© `)
	hero.FormatInt(int64(args.Year()), _buffer)
	_buffer.WriteString(` <a class="text-white" href="https://twitter.com/CodeHex">CodeHex</a></p>
  </footer>  
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
</body>
</html>`)
	w.Write(_buffer.Bytes())

}
