// Code generated by protoc-gen-go. DO NOT EDIT.
// source: collection.proto

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	collection.proto

It has these top-level messages:
	RequestFromDevice
	ResultResponse
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RequestFromDevice struct {
	Payload    string `protobuf:"bytes,1,opt,name=Payload" json:"Payload,omitempty"`
	DeviceID   string `protobuf:"bytes,2,opt,name=DeviceID" json:"DeviceID,omitempty"`
	RemoteAddr string `protobuf:"bytes,3,opt,name=RemoteAddr" json:"RemoteAddr,omitempty"`
}

func (m *RequestFromDevice) Reset()                    { *m = RequestFromDevice{} }
func (m *RequestFromDevice) String() string            { return proto.CompactTextString(m) }
func (*RequestFromDevice) ProtoMessage()               {}
func (*RequestFromDevice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RequestFromDevice) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func (m *RequestFromDevice) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

func (m *RequestFromDevice) GetRemoteAddr() string {
	if m != nil {
		return m.RemoteAddr
	}
	return ""
}

type ResultResponse struct {
	IsSuccess bool `protobuf:"varint,1,opt,name=is_success,json=isSuccess" json:"is_success,omitempty"`
}

func (m *ResultResponse) Reset()                    { *m = ResultResponse{} }
func (m *ResultResponse) String() string            { return proto.CompactTextString(m) }
func (*ResultResponse) ProtoMessage()               {}
func (*ResultResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ResultResponse) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

func init() {
	proto.RegisterType((*RequestFromDevice)(nil), "protos.RequestFromDevice")
	proto.RegisterType((*ResultResponse)(nil), "protos.ResultResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Collection service

type CollectionClient interface {
	RecvData(ctx context.Context, in *RequestFromDevice, opts ...grpc.CallOption) (*ResultResponse, error)
}

type collectionClient struct {
	cc *grpc.ClientConn
}

func NewCollectionClient(cc *grpc.ClientConn) CollectionClient {
	return &collectionClient{cc}
}

func (c *collectionClient) RecvData(ctx context.Context, in *RequestFromDevice, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := grpc.Invoke(ctx, "/protos.Collection/RecvData", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Collection service

type CollectionServer interface {
	RecvData(context.Context, *RequestFromDevice) (*ResultResponse, error)
}

func RegisterCollectionServer(s *grpc.Server, srv CollectionServer) {
	s.RegisterService(&_Collection_serviceDesc, srv)
}

func _Collection_RecvData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestFromDevice)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionServer).RecvData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Collection/RecvData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionServer).RecvData(ctx, req.(*RequestFromDevice))
	}
	return interceptor(ctx, in, info, handler)
}

var _Collection_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Collection",
	HandlerType: (*CollectionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecvData",
			Handler:    _Collection_RecvData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "collection.proto",
}

func init() { proto.RegisterFile("collection.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x50, 0xbd, 0x4a, 0xc4, 0x40,
	0x10, 0x26, 0x27, 0x68, 0x6e, 0x8a, 0x43, 0x57, 0x90, 0x5c, 0x50, 0x91, 0x54, 0x62, 0x71, 0x41,
	0xed, 0xec, 0xc4, 0x20, 0xd8, 0xc9, 0xda, 0xd8, 0xc9, 0xba, 0x19, 0xc3, 0xc2, 0x5e, 0x26, 0x66,
	0x26, 0x01, 0x5b, 0x5f, 0xc1, 0x47, 0xf3, 0x15, 0x7c, 0x10, 0x71, 0x17, 0xcf, 0x80, 0xd5, 0xf0,
	0xfd, 0xc0, 0xf7, 0xcd, 0x07, 0xbb, 0x96, 0xbc, 0x47, 0x2b, 0x8e, 0xda, 0x55, 0xd7, 0x93, 0x90,
	0xda, 0x0e, 0x87, 0xf3, 0xc3, 0x86, 0xa8, 0xf1, 0x58, 0x9a, 0xce, 0x95, 0xa6, 0x6d, 0x49, 0xcc,
	0x8f, 0x89, 0xa3, 0xab, 0x70, 0xb0, 0xa7, 0xf1, 0x75, 0x40, 0x96, 0xdb, 0x9e, 0xd6, 0x15, 0x8e,
	0xce, 0xa2, 0xca, 0x60, 0xe7, 0xde, 0xbc, 0x79, 0x32, 0x75, 0x96, 0x9c, 0x24, 0xa7, 0x73, 0xfd,
	0x0b, 0x55, 0x0e, 0x69, 0xf4, 0xdc, 0x55, 0xd9, 0x2c, 0x48, 0x1b, 0xac, 0x8e, 0x01, 0x34, 0xae,
	0x49, 0xf0, 0xba, 0xae, 0xfb, 0x6c, 0x2b, 0xa8, 0x13, 0xa6, 0x28, 0x61, 0xa1, 0x91, 0x07, 0x2f,
	0x1a, 0xb9, 0xa3, 0x96, 0x51, 0x1d, 0x01, 0x38, 0x7e, 0xe2, 0xc1, 0x5a, 0x64, 0x0e, 0x51, 0xa9,
	0x9e, 0x3b, 0x7e, 0x88, 0xc4, 0xc5, 0x0b, 0xc0, 0xcd, 0xe6, 0x2b, 0xf5, 0x08, 0xa9, 0x46, 0x3b,
	0x56, 0x46, 0x8c, 0x5a, 0xc6, 0xf6, 0xbc, 0xfa, 0xd7, 0x3d, 0x3f, 0xf8, 0x93, 0xa6, 0x59, 0xc5,
	0xf2, 0xfd, 0xf3, 0xeb, 0x63, 0xb6, 0x5f, 0x2c, 0xc2, 0x10, 0xe3, 0x79, 0x39, 0x62, 0x83, 0x62,
	0xae, 0x92, 0xb3, 0xe7, 0xb8, 0xd4, 0xe5, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x18, 0x33, 0x4b,
	0xba, 0x44, 0x01, 0x00, 0x00,
}
